In [53]:
import torch
torch.__version__

'2.2.0.dev20231118'

In [54]:
x = [[1,2],[3,4]]
y = torch.tensor(x)
print(y,y.type)

tensor([[1, 2],
        [3, 4]]) <built-in method type of Tensor object at 0x138c4fa10>


In [55]:
x = torch.zeros(2,3)
print(x)

x = torch.tensor([1,2,3])
y = torch.zeros_like(x)

print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0, 0, 0])


In [56]:
x = torch.ones(2,3)
print('x=',x)

x= tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [57]:
x = torch.randn(2,3)
x

tensor([[ 1.3331,  0.2929,  0.5627],
        [ 0.3387, -0.3099,  0.0162]])

In [58]:
x = torch.rand(2,3)
x

tensor([[0.0334, 0.6844, 0.5760],
        [0.7546, 0.3047, 0.2164]])

In [59]:
x = torch.rand(2,3,4)
print(x.shape)
print(x.size())
print(x.ndimension())
print(x.numel())
print(x.nelement())

torch.Size([2, 3, 4])
torch.Size([2, 3, 4])
3
24
24


In [60]:
x = torch.tensor([[1,2,3],[3,4,5]])
print('x=',x)

y = x.t()
print('y=',y)

z = x.transpose(0,1)
print('z=',z)


x= tensor([[1, 2, 3],
        [3, 4, 5]])
y= tensor([[1, 3],
        [2, 4],
        [3, 5]])
z= tensor([[1, 3],
        [2, 4],
        [3, 5]])


In [61]:
x = torch.rand(1,2,3)
y = torch.transpose(x,1,2)
print(y.shape)

torch.Size([1, 3, 2])


In [62]:
x.transpose_(1,2)
print(x.shape)

torch.Size([1, 3, 2])


In [63]:
x = torch.LongTensor(2,3)
x.fill_(-1)

print(x.type(),x.dtype)
print(x)

torch.LongTensor torch.int64
tensor([[-1, -1, -1],
        [-1, -1, -1]])


In [64]:
y = x.int()
z = x.float()

print(y.dtype,z.dtype)

torch.int32 torch.float32


In [65]:
x = torch.randn(2,3)
y = x.to('mps')
print(y.type(),x.type())
z = y.to('cpu')
print(z.type())

torch.mps.FloatTensor torch.FloatTensor
torch.FloatTensor


In [66]:
mps = torch.device('mps')
cpu = torch.device('cpu')

x = torch.randn(2,3,device=mps)
y = torch.randn(2,3,device=cpu)
z = x + y.to(mps)
print(z.type())

torch.mps.FloatTensor


In [67]:
import numpy as np
x = np.array([[1,2,3],[3,4,5]])

y = torch.from_numpy(x)
print(y)
print(x)

tensor([[1, 2, 3],
        [3, 4, 5]])
[[1 2 3]
 [3 4 5]]


In [68]:
z = y.numpy()
print(z)

[[1 2 3]
 [3 4 5]]


In [69]:
y.fill_(0)
print(y,'\n')
print(x,'\n')
print(z,'\n')

tensor([[0, 0, 0],
        [0, 0, 0]]) 

[[0 0 0]
 [0 0 0]] 

[[0 0 0]
 [0 0 0]] 



In [70]:
x = torch.tensor([[1],[2]])
print(x)
y = torch.tensor([[3],[4]])

tensor([[1],
        [2]])


In [71]:
print(x.shape)
print(x.type())

x = x.float()
y = y.float()
print(x)
print(y)

torch.Size([2, 1])
torch.LongTensor
tensor([[1.],
        [2.]])
tensor([[3.],
        [4.]])


In [72]:
z1 = x + y
print('z1',z1)
z2 = x * y
print('z2',z2) 

z1 tensor([[4.],
        [6.]])
z2 tensor([[3.],
        [8.]])


In [73]:
z1 = torch.mm(x,y.t())
z2 = torch.mm(x.t(),y)
print(z1)
print(z2)

tensor([[3., 4.],
        [6., 8.]])
tensor([[11.]])


In [74]:
x = torch.tensor([[1,2,3],[3,4,5]]).float()

x1 = x.sum()
z2 = x.mean()
print(x1)
print(z2)

tensor(18.)
tensor(3.)


dim=0 指的是沿着行的方向（向下），也就是列。

dim=1 指的是沿着列的方向（向右），也就是行。

In [75]:
print(x.sum(dim=1))
print(x.sum(dim=0))
x = torch.tensor([[1,2,3],[3,4,5]]).float()

tensor([ 6., 12.])
tensor([4., 6., 8.])


In [76]:
print(x.max())
print(x.max(dim=1))

tensor(5.)
torch.return_types.max(
values=tensor([3., 5.]),
indices=tensor([2, 2]))


In [77]:
x = torch.tensor([1.0,2.0])
y = x.mul(10)
print(y)



tensor([10., 20.])


In [78]:
print(x)
x.mul_(10)
print(x)

tensor([1., 2.])
tensor([10., 20.])


In [79]:
x = torch.tensor([[1],[2]])
y = torch.tensor([[3],[4]])

print(x + y)
print(torch.add(x,y))
print(x.add_(y))
z = torch.LongTensor(2,1)
print(torch.add(x,y,out=z))


tensor([[4],
        [6]])
tensor([[4],
        [6]])
tensor([[4],
        [6]])
tensor([[ 7],
        [10]])


In [80]:
x = torch.tensor([4.0,9.0])
print(x.sqrt())

print(x.log10())

tensor([2., 3.])
tensor([0.6021, 0.9542])


In [81]:
x = torch.tensor([-4.0,9.0])
print(x.relu())

tensor([0., 9.])


In [82]:
x =torch.rand(2,3,4)
print(x[1].shape)

torch.Size([3, 4])


In [83]:
print(x[1,0:2,:].shape)

torch.Size([2, 4])


In [84]:
x = torch.tensor([[1.,2.,3.],[4.,5.,6.]])
z1 = x.view(3,2)
z2 = x.view(6)
z3 = x.view(2,1,3)
print(x.shape)
print(z1.shape)
print(z2.shape)

torch.Size([2, 3])
torch.Size([3, 2])
torch.Size([6])


In [85]:
print(x)
print(z1)
print(z2)
print(z3)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([1., 2., 3., 4., 5., 6.])
tensor([[[1., 2., 3.]],

        [[4., 5., 6.]]])


In [86]:
x = torch.randn(2,3)
z1 = x.view(-1,6)
z2 = x.view(3,-1)
print(z1.shape)
print(z2.shape)

torch.Size([1, 6])
torch.Size([3, 2])


In [87]:
x = torch.ones(3,1,2)
print(x)

tensor([[[1., 1.]],

        [[1., 1.]],

        [[1., 1.]]])


In [88]:
y = x.resize_(1,2)
y.fill_(0)

print(x)
print(y)

tensor([[0., 0.]])
tensor([[0., 0.]])


In [89]:
y = x.resize_(8)
y.fill_(0)

print(y)
print(x)


tensor([0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0.])


In [90]:
x = torch.ones(2,3)
y = torch.randn(3,4)

x.resize_as_(y)


tensor([[1., 1., 1., 1.],
        [1., 1., 0., 0.],
        [0., 0., 0., 0.]])

In [91]:
x = torch.randn(3,1,2)
z1 = x.squeeze()
z2 = z1.unsqueeze(0)

print(x.shape)
print(z1.shape)
print(z2.shape)

torch.Size([3, 1, 2])
torch.Size([3, 2])
torch.Size([1, 3, 2])


In [92]:
torch.save(x,'x.pkl')
torch.save(y,'y.pkl')

In [93]:
x_new = torch.load('x.pkl')
y_new = torch.load('y.pkl')

print(x_new,'\n')
print(y_new)

tensor([[[ 0.5835, -0.8082]],

        [[ 1.6106,  0.1673]],

        [[ 0.5908, -1.7824]]]) 

tensor([[ 1.1762, -1.2879,  0.0597, -0.9497],
        [ 0.2128, -0.2893,  0.8912, -1.2769],
        [-0.8007, -0.9657, -0.6785,  0.5429]])


In [94]:
ls

Autograd.ipynb            optim.ipynb               y.pkl
Tensor.ipynb              x.pkl                     神经网络模块.ipynb


In [97]:
import pickle

with open('y_new.pkl','wb') as f:
    pickle.dump(y_new,f)
    

In [98]:
ls

Autograd.ipynb            x.pkl                     神经网络模块.ipynb
Tensor.ipynb              y.pkl
optim.ipynb               y_new.pkl


In [99]:
with open('y_new.pkl','rb') as f:
    y_new = pickle.load(f)
    
print(y_new)

tensor([[ 1.1762, -1.2879,  0.0597, -0.9497],
        [ 0.2128, -0.2893,  0.8912, -1.2769],
        [-0.8007, -0.9657, -0.6785,  0.5429]])
