In [11]:
import torch
from torch.autograd import Variable
# 定义变量x
x = Variable(torch.Tensor([3]), requires_grad=True)
# 定义函数
f = x*x - x 
# 求导数
f.backward()
# 打印导数
print(x)
print(f)
print(f.data[0])
print(x.grad.data[0])
print(x.grad)

tensor([3.], requires_grad=True)
tensor([6.], grad_fn=<SubBackward0>)
tensor(6.)
tensor(5.)
tensor([5.])


In [16]:
value = torch.Tensor([1,2])
x = Variable(value, requires_grad=True)
print(x.data is value)

False


In [5]:
y = x + x
z = x ** 3
print(y.grad_fn)
print(z.grad_fn)

In [6]:
x.is_leaf, y.is_leaf

(True, False)

In [7]:
x.grad_fn, y.grad_fn

(None, <AddBackward0 at 0x1174ff430>)

In [8]:
y.grad_fn.next_functions

((<AccumulateGrad at 0x1174febf0>, 0), (<AccumulateGrad at 0x1174febf0>, 0))

In [15]:
x = torch.tensor(3.0, requires_grad=True)
f = x * x - x
print (f)
f.backward()
print (x.grad)

tensor(6., grad_fn=<SubBackward0>)
tensor(5.)


In [13]:
x = torch.tensor([1.0], requires_grad=True)
y = x + x
z = x ** 3

y.backward()

print(x.grad.data)
x.grad.zero_()
z.backward()



print(x.grad.data)
 

tensor([2.])
tensor([3.])


In [26]:
x = torch.tensor([1.,2.,3.],requires_grad=True)
w = torch.tensor([0.,0.,0.],requires_grad=True)

f = (x+w)*(x+2*w)
f = f.sum()

df = torch.autograd.grad(f,[x,w],create_graph=True)

In [27]:
df

(tensor([2., 4., 6.], grad_fn=<AddBackward0>),
 tensor([3., 6., 9.], grad_fn=<AddBackward0>))

In [28]:
G = df[0].pow(2).sum()
G.backward()

print(x.grad)

tensor([ 8., 16., 24.])


In [29]:
from torch.autograd import Function
class MulAdd(Function):
    @staticmethod
    def forward(ctx,w,x,b):
        ctx.save_for_backward(w,x)
        output = w * x + b
        return output
    @staticmethod
    def backward(ctx,grad_output):
        w,x = ctx.saved_tensors
        grad_w = grad_output * x
        grad_x = grad_output * w
        grad_b = grad_output * 1
        return grad_w,grad_x,grad_b

In [31]:
x = torch.tensor(1.)
w = torch.tensor(2.,requires_grad=True)
b = torch.tensor(3.,requires_grad=True)
z = MulAdd.apply(w,x,b)
z.backward()
x.grad,w.grad,b.grad

(None, tensor(1.), tensor(1.))

In [ ]:
x = torch.tensor(3.0, requires_grad=True)

In [ ]:
x = torch.tensor(3.0, requires_grad=True)

In [39]:
value = torch.ones(2)
x = value.requires_grad_()
f = x * x - x
f = f.sum()
f.backward()
print(x.grad.data)

tensor([1., 1.])


In [40]:
x =torch.ones(2,requires_grad=True)
f = x * x - x
f.backward(torch.ones_like(f))
print(x.grad.data)


tensor([1., 1.])
