In [36]:
# 通过固定宽度分箱对计数值进行区间量化
import numpy as np


In [37]:
# 生成20个随机整数，均匀分布在0-99之间
small_counts = np.random.randint(0, 100, 20)
small_counts


array([58, 66, 13, 46, 35, 64, 48, 50, 25, 19, 51, 70, 79, 42, 22, 80, 18,
       81, 38, 72])

In [38]:
# 通过除法映射到间隔均匀的分箱中，每个分箱的取值范围都是0-9
np.floor_divide(small_counts, 10)


array([5, 6, 1, 4, 3, 6, 4, 5, 2, 1, 5, 7, 7, 4, 2, 8, 1, 8, 3, 7],
      dtype=int32)

In [39]:
# 横跨若干数量级的计数值数箱
large_counts = [296, 8286, 64011, 80, 3, 725, 867, 2215, 7689, 11495, 91897,
                44, 28, 7971, 926, 122, 22222]
#通过对数函数映射到指数宽度分箱
np.floor(np.log10(large_counts))

array([2., 3., 4., 1., 0., 2., 2., 3., 3., 4., 4., 1., 1., 3., 2., 2., 4.])

In [40]:
import pandas as pd
# 将计数值映射为分位数
pd.qcut(large_counts, q=4, labels=False)


array([1, 2, 3, 0, 0, 1, 1, 2, 2, 3, 3, 0, 0, 2, 1, 0, 3], dtype=int64)

In [41]:
large_counts_series = pd.Series(large_counts)
large_counts_series.quantile([0.25, 0.5, 0.75])

0.25     122.0
0.50     926.0
0.75    8286.0
dtype: float64

In [44]:
help(pd.qcut)

Help on function qcut in module pandas.core.reshape.tile:

qcut(x, q, labels=None, retbins: bool = False, precision: int = 3, duplicates: str = 'raise')
    Quantile-based discretization function.
    
    Discretize variable into equal-sized buckets based on rank or based
    on sample quantiles. For example 1000 values for 10 quantiles would
    produce a Categorical object indicating quantile membership for each data point.
    
    Parameters
    ----------
    x : 1d ndarray or Series
    q : int or list-like of float
        Number of quantiles. 10 for deciles, 4 for quartiles, etc. Alternately
        array of quantiles, e.g. [0, .25, .5, .75, 1.] for quartiles.
    labels : array or False, default None
        Used as labels for the resulting bins. Must be of the same length as
        the resulting bins. If False, return only integer indicators of the
        bins. If True, raises an error.
    retbins : bool, optional
        Whether to return the (bins, labels) or not. Can b